// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcjwpR82_XkGV-PCi38TV6pJQyO4BXK14',
    appId: '1:237802919844:web:44f4ec8fe146a60dc75331',
    messagingSenderId: '237802919844',
    projectId: 'homie-studio---project',
    authDomain: 'homie-studio---project.firebaseapp.com',
    storageBucket: 'homie-studio---project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8P5W0OcEGCnJXYZWLnnXkWNbxVNhrTcY',
    appId: '1:237802919844:android:f061641ac6857e16c75331',
    messagingSenderId: '237802919844',
    projectId: 'homie-studio---project',
    storageBucket: 'homie-studio---project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA75ZnuqBlfOfWMLHRnR3g99OtJvt5S5ZY',
    appId: '1:237802919844:ios:6e257be48f81112ac75331',
    messagingSenderId: '237802919844',
    projectId: 'homie-studio---project',
    storageBucket: 'homie-studio---project.appspot.com',
    iosClientId: '237802919844-lfuu9rujfnspop2q1vitpjhbahs1ea1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA75ZnuqBlfOfWMLHRnR3g99OtJvt5S5ZY',
    appId: '1:237802919844:ios:6e257be48f81112ac75331',
    messagingSenderId: '237802919844',
    projectId: 'homie-studio---project',
    storageBucket: 'homie-studio---project.appspot.com',
    iosClientId: '237802919844-lfuu9rujfnspop2q1vitpjhbahs1ea1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
